"""Fixtures for Phase 2 tests.

Synthetic documents, never the real 94 MiB corpus. Two reasons: `data/` is
gitignored, so a clean clone has none of it and tests keyed to it would fail on
checkout; and a test asserting against a live filing would break when the
September final orders republish it — which is exactly the change Phase 5 exists
to detect, not a test failure.
"""

from __future__ import annotations

import json
import zlib
from pathlib import Path

import pytest
from openpyxl import Workbook

# ---------------------------------------------------------------------------
# Minimal PDFs
# ---------------------------------------------------------------------------


def make_pdf(path: Path, pages: list[str]) -> Path:
    """Write a small, valid, text-extractable PDF.

    Hand-built rather than generated by a library so the tests carry no extra
    dependency and so the byte layout is predictable enough to corrupt on purpose
    (see `truncated_pdf`).
    """
    objects: list[bytes] = []

    def add(body: bytes) -> int:
        objects.append(body)
        return len(objects)

    font_id = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
                  b"/Encoding /WinAnsiEncoding >>")

    page_ids: list[int] = []
    content_ids: list[int] = []
    for text in pages:
        lines = text.split("\n")
        parts = [b"BT /F1 11 Tf 40 750 Td 14 TL"]
        for line in lines:
            escaped = (
                line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
            ).encode("latin-1", "replace")
            parts.append(b"(" + escaped + b") Tj T*")
        parts.append(b"ET")
        stream = b"\n".join(parts)
        compressed = zlib.compress(stream)
        content_ids.append(
            add(b"<< /Length %d /Filter /FlateDecode >>\nstream\n" % len(compressed)
                + compressed + b"\nendstream")
        )

    pages_id = len(objects) + len(pages) + 1
    for content_id in content_ids:
        page_ids.append(
            add(
                b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 612 792] "
                b"/Resources << /Font << /F1 %d 0 R >> >> /Contents %d 0 R >>"
                % (pages_id, font_id, content_id)
            )
        )

    kids = b" ".join(b"%d 0 R" % pid for pid in page_ids)
    actual_pages_id = add(
        b"<< /Type /Pages /Kids [%s] /Count %d >>" % (kids, len(page_ids))
    )
    catalog_id = add(b"<< /Type /Catalog /Pages %d 0 R >>" % actual_pages_id)

    # Patch each page's /Parent to the real Pages object id.
    for pid in page_ids:
        objects[pid - 1] = objects[pid - 1].replace(
            b"/Parent %d 0 R" % pages_id, b"/Parent %d 0 R" % actual_pages_id
        )

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % index + body + b"\nendobj\n"

    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += b"%010d 00000 n \n" % offset
    out += (
        b"trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n"
        % (len(objects) + 1, catalog_id, xref_at)
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(out))
    return path


# ---------------------------------------------------------------------------
# Minimal URRT workbook
# ---------------------------------------------------------------------------


def make_urrt(
    path: Path,
    *,
    legal_name: str = "Test Health Plan, Inc.",
    hios: str = "12345",
    plans: list[dict] | None = None,
    submission_rate: object = "#VALUE!",
) -> Path:
    """A workbook with the URRT's structure: header block plus a transposed Wksh 2."""
    plans = plans or [
        {"plan_id": "12345OR0010001", "metal": "Silver", "rate": 0.1152, "enroll": 100},
        {"plan_id": "12345OR0010002", "metal": "Gold", "rate": 0.0875, "enroll": 250},
    ]
    book = Workbook()

    sheet1 = book.active
    sheet1.title = "Wksh 1 - Market Experience"
    sheet1["B1"] = "Unified Rate Review v8.2 [assistive technology users, see cell A1]"
    sheet1["B3"], sheet1["C3"] = "Company Legal Name:", legal_name
    sheet1["B4"], sheet1["C4"] = "HIOS Issuer ID:", int(hios)
    sheet1["D4"], sheet1["E4"] = "State:", "OR"
    sheet1["B5"], sheet1["C5"] = "Effective Date of Rate Change(s):", "1/1/2027"
    sheet1["D5"], sheet1["E5"] = "Market: ", "Individual"

    sheet2 = book.create_sheet("Wksh 2 - Plan Product Info")
    rows = {
        "1.1": ("Product Name", "product"),
        "1.2": ("Product ID", "product_id"),
        "1.3": ("Plan Name", "plan_name"),
        "1.4": ("Plan ID (Standard Component ID)", "plan_id"),
        "1.5": ("Metal", "metal"),
        "1.6": ("AV Metal Value", "av"),
        "1.7": ("Plan Category", "category"),
        "1.8": ("Plan Type", "plan_type"),
        "1.9": ("Exchange Plan?", "exchange"),
        "1.11": ("Cumulative Rate Change %  (over 12 mos prior)", "rate"),
        "1.13": ("Submission Level Rate Increase %", None),
        "2.12": ("Current Enrollment", "enroll"),
        "3.11": ("Plan Adjusted Index Rate", "pair"),
    }
    for offset, (field_no, (label, _)) in enumerate(rows.items(), start=10):
        sheet2.cell(row=offset, column=2, value=field_no)
        sheet2.cell(row=offset, column=3, value=label)

    for plan_index, plan in enumerate(plans):
        column = 5 + plan_index
        for offset, (field_no, (_, key)) in enumerate(rows.items(), start=10):
            if field_no == "1.13":
                if plan_index == 0:
                    sheet2.cell(row=offset, column=column, value=submission_rate)
                continue
            defaults = {
                "product": "Test PPO",
                "product_id": plan["plan_id"][:10],
                "plan_name": f"Plan {plan_index + 1}",
                "metal": plan.get("metal", "Silver"),
                "av": 0.70,
                "category": "Renewing",
                "plan_type": "PPO",
                "exchange": "Yes",
                "pair": "$1,234.56",
            }
            value = plan.get(key, defaults.get(key))
            if value is not None:
                sheet2.cell(row=offset, column=column, value=value)

    sheet3 = book.create_sheet("Wksh 3 - Rating Areas")
    sheet3["A5"], sheet3["B5"] = "Rating Area", "Rating Factor"
    sheet3["A6"], sheet3["B6"] = "Rating Area 1", 0.952
    sheet3["A7"], sheet3["B7"] = "Rating Area 2", 1.009

    path.parent.mkdir(parents=True, exist_ok=True)
    book.save(path)
    return path


# ---------------------------------------------------------------------------
# A minimal ingest store + manifest
# ---------------------------------------------------------------------------


MANIFEST_DEFAULTS = {
    "manifest_schema_version": 1,
    "carrier_label_raw": "Test Carrier",
    "plan_year": 2027,
    "market": "individual",
    "source_item_key": "1",
    "etag": '"0x8DEE41154D40D80"',
    "last_modified": "Fri, 17 Jul 2026 14:40:22 GMT",
    "sharepoint_version": None,
    "prior_content_hash": None,
    "attempt_count": 1,
    "error": None,
}


def write_manifest_row(path: Path, **overrides) -> dict:
    row = {
        **MANIFEST_DEFAULTS,
        "run_id": "20260820T170641Z",
        "retrieved_at": "20260820T170645Z",
        "state": "OR",
        "filing_id": "or-2027-indv-test",
        "document_role": "urrt",
        "source_url": "https://example.invalid/urrt.xlsm",
        "http_status": 200,
        "content_type": "application/vnd.ms-excel.sheet.macroEnabled.12",
        "content_length": 1000,
        "content_hash": "sha256:" + "0" * 64,
        "unchanged": False,
        "stored_path": "OR/or-2027-indv-test/20260820T170641Z/urrt.xlsm",
    }
    row.update(overrides)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row) + "\n")
    return row


@pytest.fixture
def data_root(tmp_path: Path) -> Path:
    root = tmp_path / "raw"
    root.mkdir(parents=True, exist_ok=True)
    return root


@pytest.fixture
def output_root(tmp_path: Path) -> Path:
    return tmp_path / "extracted"


@pytest.fixture
def urrt_path(data_root: Path) -> Path:
    return make_urrt(data_root / "OR" / "or-2027-indv-test" / "20260820T170641Z" / "urrt.xlsm")


@pytest.fixture
def truncated_pdf(tmp_path: Path) -> Path:
    """A PDF cut off mid-file. Used to prove a crash becomes a `failed` row."""
    good = make_pdf(tmp_path / "good.pdf", ["Hello world"])
    broken = tmp_path / "truncated.pdf"
    broken.write_bytes(good.read_bytes()[: len(good.read_bytes()) // 3])
    return broken


@pytest.fixture
def corrupt_workbook(tmp_path: Path) -> Path:
    """Not a zip at all, but named .xlsm."""
    path = tmp_path / "corrupt.xlsm"
    path.write_bytes(b"this is definitely not a workbook")
    return path
